
inpaint:
  "sd_model_key": "./sd-1.5" #modify to your SD-1.5 path
  "image_path":
  "mask_path":
  "ip_adapter_image_path": 
  "prompt":  'pure grey concrete'
  "negative_prompt": "strong light, Bright light, intense light, dazzling light, brilliant light, radiant light, Shade, darkness, silhouette, dimness, obscurity, shadow, glasses"
  "seed": -1
  "width": 1024
  "height": 1024
  "num_images_per_prompt": 1
  "guidance_scale": 3.0
  "num_inference_steps": 20
  "denoising_strength": 1.0
  "controlnet_units":
    - "preprocessor": "none"
      "controlnet_key": "./uv_controlnet"  #https://huggingface.co/Urban-World/UrbanWorld-UV-control
      "condition_image_path":
      "weight": 1.0
    - "preprocessor": "inpaint_global_harmonious"
      "controlnet_key": "./sd15_inpaint"  #https://huggingface.co/lllyasviel/control_v11p_sd15_inpaint
      "condition_image_path": ""
      "weight": 0.5

img2img:
  "sd_model_key": "./realisticVision" #https://huggingface.co/GeorgeQi/realisticVisionV13_v13
  # run
  "image_path":
  "ip_adapter_image_path": 
  "prompt":  "UV map, high quality, best quality"
  "negative_prompt": "blur, low quality, noisy image, over-exposed, shadow"
  "seed": -1
  "width": 1024
  "height": 1024
  "num_images_per_prompt": 1
  "guidance_scale": 7.0
  "num_inference_steps": 20
  "denoising_strength": 0.75
  "controlnet_units":
    - "preprocessor": "none"
      "controlnet_key": "./uv_controlnet" #https://huggingface.co/Urban-World/UrbanWorld-UV-control
      "condition_image_path":
      "weight": 1.0
    - "preprocessor": "none"
      "controlnet_key": "./sd15_tile"  #https://huggingface.co/lllyasviel/control_v11f1e_sd15_tile
      "condition_image_path":
      "weight": 1.0
